---
# roles/vatrix_teardown/tasks/main.yml

- name: Stop Vatrix service
  systemd:
    name: vatrix
    state: stopped
  ignore_errors: true

- name: Disable Vatrix service
  systemd:
    name: vatrix
    enabled: no
  ignore_errors: true

- name: Remove Vatrix systemd unit
  file:
    path: /etc/systemd/system/vatrix.service
    state: absent
  ignore_errors: true

- name: Remove Vatrix virtual environment
  file:
    path: /opt/vatrix/venv
    state: absent
  ignore_errors: true

- name: Remove Vatrix app directory
  file:
    path: /opt/vatrix
    state: absent
  ignore_errors: true

- name: Remove Vatrix log directory
  file:
    path: /var/log/vatrix
    state: absent
  ignore_errors: true

- name: Reload systemd to finalize cleanup
  systemd:
    daemon_reload: yes
