# roles/qdrant_teardown/tasks/main.yml

- name: Stop and remove Qdrant + Vatrix Gateway Docker stack
  community.docker.docker_compose_v2:
    project_src: "{{ qdrant_gateway_compose_path }}"
    state: absent
    remove_images: all
    remove_volumes: true
    remove_orphans: true
  register: teardown_result
  ignore_errors: true

- name: Print teardown result (if any)
  debug:
    var: teardown_result
  when: teardown_result is defined and teardown_result.stdout is defined

- name: Ensure Docker Compose directory is removed
  file:
    path: "{{ qdrant_gateway_compose_path }}"
    state: absent
  ignore_errors: true